"""rent_price table

Revision ID: 13e7c1526fef
Revises: 2bd709bb5837
Create Date: 2026-09-07 15:26:57.631183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e7c1526fef'
down_revision: Union[str, Sequence[str], None] = '2bd709bb5837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_price',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_type', sa.String(), nullable=False),
    sa.Column('cls_id', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('region_path', sa.String(), nullable=False),
    sa.Column('region_level', sa.Integer(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('rent_per_m2', sa.Float(), nullable=True),
    sa.Column('vacancy_rate', sa.Float(), nullable=True),
    sa.Column('rent_statbl_id', sa.String(), nullable=True),
    sa.Column('vacancy_statbl_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['district.district_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rent_price_type_period', 'rent_price', ['building_type', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rent_price_type_period', table_name='rent_price')
    op.drop_table('rent_price')
    # ### end Alembic commands ###
