"""shock_event tables and interest_rate

Revision ID: 2bd709bb5837
Revises: 5e26dfc27428
Create Date: 2026-09-07 15:11:59.017136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd709bb5837'
down_revision: Union[str, Sequence[str], None] = '5e26dfc27428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_rate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rate_type', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('stat_code', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interest_rate_type_period', 'interest_rate', ['rate_type', 'period'], unique=False)
    op.create_table('shock_event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_shock_event_layer_start', 'shock_event', ['layer', 'start_date'], unique=False)
    op.create_table('shock_event_industry',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['shock_event.event_id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'industry_id')
    )
    op.create_table('shock_event_region',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['shock_event.event_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('event_id', 'region_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shock_event_region')
    op.drop_table('shock_event_industry')
    op.drop_index('ix_shock_event_layer_start', table_name='shock_event')
    op.drop_table('shock_event')
    op.drop_index('ix_interest_rate_type_period', table_name='interest_rate')
    op.drop_table('interest_rate')
    # ### end Alembic commands ###
