"""store table + district.opn_authority_code

Revision ID: 43367fbe8af0
Revises: 45043069cde6
Create Date: 2026-08-25 16:40:14.887474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43367fbe8af0'
down_revision: Union[str, Sequence[str], None] = '45043069cde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['district.district_code'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['industry_subcategory.subcategory_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('ix_store_industry_district_updated', 'store', ['industry_id', 'district_code', 'source_updated_at'], unique=False)
    op.add_column('district', sa.Column('opn_authority_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'district', ['opn_authority_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'district', type_='unique')
    op.drop_column('district', 'opn_authority_code')
    op.drop_index('ix_store_industry_district_updated', table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
