"""convenience_store table

Revision ID: 5a21ef1efab1
Revises: a6376277270d
Create Date: 2026-09-07 16:56:11.322197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a21ef1efab1'
down_revision: Union[str, Sequence[str], None] = 'a6376277270d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenience_store',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('road_address', sa.String(), nullable=True),
    sa.Column('jibun_address', sa.String(), nullable=True),
    sa.Column('source_stdr_ym', sa.String(), nullable=False),
    sa.Column('first_seen_on', sa.Date(), nullable=False),
    sa.Column('last_seen_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('ix_convenience_store_region_last_seen', 'convenience_store', ['region_code', 'last_seen_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_convenience_store_region_last_seen', table_name='convenience_store')
    op.drop_table('convenience_store')
    # ### end Alembic commands ###
