"""academy_course table

Revision ID: 5e26dfc27428
Revises: 945d0433e675
Create Date: 2026-09-07 14:48:38.664502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e26dfc27428'
down_revision: Union[str, Sequence[str], None] = '945d0433e675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_course',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('tuition_fee', sa.Integer(), nullable=True),
    sa.Column('target_grade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_academy_course_store_id'), 'academy_course', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academy_course_store_id'), table_name='academy_course')
    op.drop_table('academy_course')
    # ### end Alembic commands ###
