"""rag_chunk table

Revision ID: 66a23fb0c6e9
Revises: 5a21ef1efab1
Create Date: 2026-09-15 09:50:54.681631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '66a23fb0c6e9'
down_revision: Union[str, Sequence[str], None] = '5a21ef1efab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunk',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedded_by', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_rag_chunk_source', 'rag_chunk', ['source_type', 'source_id'], unique=False)
    op.execute("CREATE INDEX ix_rag_chunk_embedding_hnsw ON rag_chunk USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rag_chunk_embedding_hnsw', table_name='rag_chunk')
    op.drop_index('ix_rag_chunk_source', table_name='rag_chunk')
    op.drop_table('rag_chunk')
    # ### end Alembic commands ###
