"""population_stat table

Revision ID: 945d0433e675
Revises: a66c8cd01cd2
Create Date: 2026-09-07 14:38:17.880758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945d0433e675'
down_revision: Union[str, Sequence[str], None] = 'a66c8cd01cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_stat',
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age_from', sa.Integer(), nullable=False),
    sa.Column('age_to', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('region_code', 'period', 'gender', 'age_from')
    )
    op.create_index('ix_population_stat_period', 'population_stat', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_population_stat_period', table_name='population_stat')
    op.drop_table('population_stat')
    # ### end Alembic commands ###
