"""master layer: district, region, industry, industry_source_code, industry_subcategory

Revision ID: 9af965caa6ab
Revises: 
Create Date: 2026-08-25 16:10:33.694701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af965caa6ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_table('industry',
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_table('industry_source_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_id', 'source_system', 'code')
    )
    op.create_table('industry_subcategory',
    sa.Column('subcategory_id', sa.String(), nullable=False),
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('category_axis', sa.String(), nullable=False),
    sa.Column('target_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.PrimaryKeyConstraint('subcategory_id')
    )
    op.create_table('region',
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['district.district_code'], ),
    sa.PrimaryKeyConstraint('region_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    op.drop_table('industry_subcategory')
    op.drop_table('industry_source_code')
    op.drop_table('industry')
    op.drop_table('district')
    # ### end Alembic commands ###
