"""tobacco_retailer table

Revision ID: a6376277270d
Revises: 13e7c1526fef
Create Date: 2026-09-07 16:41:30.464736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6376277270d'
down_revision: Union[str, Sequence[str], None] = '13e7c1526fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tobacco_retailer',
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('designated_date', sa.Date(), nullable=True),
    sa.Column('permit_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('cancel_date', sa.Date(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('road_address', sa.String(), nullable=True),
    sa.Column('jibun_address', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['district.district_code'], ),
    sa.ForeignKeyConstraint(['region_code'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('retailer_id')
    )
    op.create_index('ix_tobacco_retailer_region_status', 'tobacco_retailer', ['region_code', 'status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tobacco_retailer_region_status', table_name='tobacco_retailer')
    op.drop_table('tobacco_retailer')
    # ### end Alembic commands ###
