"""funding_program table

Revision ID: a66c8cd01cd2
Revises: b0aeecac90e6
Create Date: 2026-09-07 13:35:42.692483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66c8cd01cd2'
down_revision: Union[str, Sequence[str], None] = 'b0aeecac90e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_program',
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('org', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('apply_period', sa.String(), nullable=False),
    sa.Column('exec_org', sa.String(), nullable=True),
    sa.Column('field_category', sa.String(), nullable=True),
    sa.Column('field_subcategory', sa.String(), nullable=True),
    sa.Column('target_text', sa.String(), nullable=True),
    sa.Column('hashtags', sa.String(), nullable=True),
    sa.Column('apply_begin', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_funding_program_open_deadline', 'funding_program', ['is_expired', 'deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_funding_program_open_deadline', table_name='funding_program')
    op.drop_table('funding_program')
    # ### end Alembic commands ###
